---
apiVersion: v1
kind: Service
metadata:
  name: earthquake-db-service
spec:
  type: ClusterIP
  selector:
    app: earthquake-db
  ports:
  - name: earthquake-db
    port: 6379
    targetPort: 6379